### ISSUE TITLE
Vue 3 (Composition API) へ完全に移行する

### ISSUE THREAD

**Issue by taiyme** [taiyme/misskey#102]
## Summary
一部のコンポーネントがOptions APIのままなので、Composition APIに置き換える(苦行)

## TODO
- [x] [`@/components/MkContainer.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkContainer.vue)
- [ ] [`@/components/MkDateSeparatedList.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkDateSeparatedList.vue)
- [ ] [`@/components/MkFolder.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkFolder.vue)
- [x] [`@/components/MkFormDialog.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkFormDialog.vue)
- [x] [`@/components/MkFormula.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkFormula.vue)
- [x] [`@/components/MkFormulaCore.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkFormulaCore.vue)
- [ ] [`@/components/MkMarquee.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkMarquee.vue)
- [ ] [`@/components/MkNumberDiff.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkNumberDiff.vue)
- [ ] [`@/components/MkObjectView.value.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkObjectView.value.vue)
- [ ] [`@/components/MkPagePreview.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkPagePreview.vue)
- [x] [`@/components/MkPostFormAttaches.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkPostFormAttaches.vue)
- [x] [`@/components/MkPostFormDialog.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkPostFormDialog.vue)
- [ ] [`@/components/MkSample.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkSample.vue)
- [ ] [`@/components/MkSuperMenu.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkSuperMenu.vue)
- [ ] [`@/components/MkTab.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/MkTab.vue)
- [x] [`@/components/form/radio.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/form/radio.vue)
- [ ] [`@/components/form/suspense.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/form/suspense.vue)
- [ ] [`@/components/global/i18n.ts`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/global/i18n.ts)
- [ ] [`@/components/page/page.block.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.block.vue)
- [ ] [`@/components/page/page.button.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.button.vue)
- [ ] [`@/components/page/page.canvas.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.canvas.vue)
- [ ] [`@/components/page/page.counter.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.counter.vue)
- [ ] [`@/components/page/page.if.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.if.vue)
- [x] [`@/components/page/page.image.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.image.vue)
- [x] [`@/components/page/page.note.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.note.vue)
- [ ] [`@/components/page/page.number-input.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.number-input.vue)
- [ ] [`@/components/page/page.post.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.post.vue)
- [ ] [`@/components/page/page.radio-button.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.radio-button.vue)
- [ ] [`@/components/page/page.section.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.section.vue)
- [ ] [`@/components/page/page.switch.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.switch.vue)
- [ ] [`@/components/page/page.text-input.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.text-input.vue)
- [ ] [`@/components/page/page.text.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.text.vue)
- [ ] [`@/components/page/page.textarea-input.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.textarea-input.vue)
- [ ] [`@/components/page/page.textarea.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.textarea.vue)
- [ ] [`@/components/page/page.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/components/page/page.vue)
- [ ] [`@/pages/about.emojis.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/pages/about.emojis.vue)
- [ ] [`@/pages/auth.form.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/pages/auth.form.vue)
- [ ] [`@/pages/auth.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/pages/auth.vue)
- [ ] [`@/pages/welcome.entrance.b.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/pages/welcome.entrance.b.vue)
- [ ] [`@/pages/welcome.entrance.c.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/pages/welcome.entrance.c.vue)
- [ ] [`@/pages/welcome.timeline.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/pages/welcome.timeline.vue)
- [ ] [`@/pages/admin/metrics.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/pages/admin/metrics.vue)
- [ ] [`@/pages/page-editor/page-editor.blocks.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/pages/page-editor/page-editor.blocks.vue)
- [ ] [`@/pages/page-editor/page-editor.container.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/pages/page-editor/page-editor.container.vue)
- [ ] [`@/pages/page-editor/page-editor.script-block.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/pages/page-editor/page-editor.script-block.vue)
- [ ] [`@/ui/classic.header.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/ui/classic.header.vue)
- [ ] [`@/ui/classic.sidebar.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/ui/classic.sidebar.vue)
- [ ] [`@/ui/classic.widgets.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/ui/classic.widgets.vue)
- [ ] [`@/ui/visitor.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/ui/visitor.vue)
- [ ] [`@/ui/visitor/a.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/ui/visitor/a.vue)
- [ ] [`@/ui/visitor/header.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/ui/visitor/header.vue)
- [ ] [`@/ui/visitor/kanban.vue`](https://github.com/taiyme/misskey/blob/taiyme-v12/packages/client/src/ui/visitor/kanban.vue)
